version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - .:/myproject
      - bundle:/usr/local/bundle
    links:
      - db

volumes:
  mysql-data:
  bundle:
